apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: terraacr2025prod.azurecr.io/myapp:v1.0.0-pr53
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret-prod